feat(workload): add default spread on workloads
cdk8s-team/cdk8s-plus pull request #1176
Opened 2022-09-20 06:13 UTC by vinayak-kukreja

Following Kubernetes [guidance](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#internal-default-constraints) to spread pods across nodes and zones for a workload. Adding a default spread property to workloads. 

Resolves https://github.com/cdk8s-team/cdk8s-plus/issues/890

Signed-off-by: Vinayak Kukreja <vinakuk@amazon.com>

2022-09-22 18:39 UTC, ryparker reviewed
👍🏻

2022-09-28 14:09 UTC, iliapolo requested changes

2022-09-28 14:09 UTC, iliapolo commented on src/workload.ts
> +  readonly defaultSpread?: boolean;
Lets call this just `spread`, similar to `select`.

2022-09-28 14:09 UTC, iliapolo commented on src/workload.ts
> +   * @default true
The default should be `false` to be more developer friendly, i.e allowing default constructs to run on a dev cluster with one node.

2022-09-29 08:42 UTC, iliapolo approved these changes

2022-09-29 08:47 UTC, merged

2022-09-29 08:48 UTC, cdk8s-automation commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|k8s-22/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/1206">](https://github.com/cdk8s-team/cdk8s-plus/pull/1206)|
|✅|k8s-23/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/1207">](https://github.com/cdk8s-team/cdk8s-plus/pull/1207)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.4 -->