Accept Container obj for Pod.add_container_fix
cdk8s-team/cdk8s-plus pull request #1512
Opened 2022-12-14 14:13 UTC by yfried

Fixes: #1508

2022-12-14 15:35 UTC, iliapolo requested changes
@yfried Unfortunately we can't do this because union types don't translate well to other languages. In Java for example this would translate to accepting an `Object`, which is not a good experience. What we usually do is just add another method with a different name that accepts the different argument.

2022-12-15 11:27 UTC, yfried commented
> @yfried Unfortunately we can't do this because union types don't translate well to other languages. In Java for example this would translate to accepting an `Object`, which is not a good experience. What we usually do is just add another method with a different name that accepts the different argument.

So instead you meant to have `attachConainer(cont: Container)` and `addContainer(cont: ContainerProps)`?
It's easy to do technically but I'm concerned that these 2 methods will look the same to new users (like me), and would raise a whole new bunch of questions/frustrations

2022-12-15 13:28 UTC, iliapolo commented
@yfried I agree adding another method might be confusing, but we can clarify the confusion with documentation. 

Ideally we would have the `addContainer` method accept a `Container`, and then have another method called `createContainer` that would accept `ContainerProps` and create the `Container`. But unfortunately we cannot break the API.

So given our limitations, I think adding the `attachXXX` methods will be an OK solution.

2022-12-18 12:12 UTC, iliapolo requested changes
@yfried Lets also add `attachInitContainer`, and we need some unit tests added here: https://github.com/cdk8s-team/cdk8s-plus/blob/k8s-25/main/test/pod.test.ts#L138

2022-12-19 11:11 UTC, iliapolo approved these changes

2022-12-19 11:12 UTC, iliapolo commented
@yfried looks good. Just need the DCO: https://github.com/cdk8s-team/cdk8s-plus/blob/k8s-25/main/CONTRIBUTING.md#developer-certificate-of-origin-dco

2022-12-20 12:29 UTC, iliapolo commented on src/pod.ts
> +    this.attachContainer(impl)
```suggestion
    this.attachContainer(impl);
```

2022-12-20 12:32 UTC, iliapolo commented
@yfried The build is failing because it detected a diff between your code and the one our linters expect. Can you run `yarn build` locally to auto-fix it?

2022-12-20 18:30 UTC, merged

2022-12-20 18:31 UTC, cdk8s-automation commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|k8s-23/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/1541">](https://github.com/cdk8s-team/cdk8s-plus/pull/1541)|
|✅|k8s-24/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/1542">](https://github.com/cdk8s-team/cdk8s-plus/pull/1542)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.5.0 -->