fix(ingress): add `ingressClassName` to `IngressProps`
cdk8s-team/cdk8s-plus pull request #2964
Opened 2023-09-25 22:11 UTC by sumupitchayan

Fixes #2856 

Currently, `IngressProps` does not have a property allowing users to pass in an `ingressClassName`. This PR fixes this and adds a unit test to verify the change.

2023-10-01 21:59 UTC, iliapolo requested changes

2023-10-01 21:59 UTC, iliapolo commented on src/ingress.ts
> +  readonly ingressClassName?: string;
"ingress" is already implied 

```suggestion
  readonly className?: string;
```

2023-10-01 21:59 UTC, iliapolo commented on src/ingress.ts
> +   * Ingress Class Name is an optional String property.
Describe the meaning, not the technicality. 

That is, what does `ingressClassName` mean? We usually lean on the k8s docs for that.

2024-02-05 13:41 UTC, pivstone commented
Hi there, looks like this PR is stale for quite some time.  
I'm wondering what's the next step for this PR? 

It will be nice we could implement it. We are moving our helm to use CDK8S, and we found CDK8S don't support `ingressClassName`. We also saw the work around. But it will be nice if we can support it directly,

2024-02-22 14:43 UTC, iliapolo approved these changes

2024-02-22 14:48 UTC, merged

2024-02-22 14:48 UTC, cdk8s-automation commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|k8s-25/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/3764">](https://github.com/cdk8s-team/cdk8s-plus/pull/3764)|
|✅|k8s-26/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/3765">](https://github.com/cdk8s-team/cdk8s-plus/pull/3765)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.5.0 -->