Add iSCSI persistentvolume and possibility to bind PVs to PVCs in any namespace
cdk8s-team/cdk8s-plus pull request #3285
Opened 2023-11-12 22:49 UTC by St0rmingBr4in

This adds the IscsiPersistentVolume class to be able to generate iSCSI backed persistent volumes.

This also adds the ability to bind a PV to a PVC in another namespace than the default one.

2024-01-17 21:46 UTC, St0rmingBr4in commented
@iliapolo Could you take a look please ?

2024-04-07 09:20 UTC, iliapolo requested changes

2024-04-07 09:20 UTC, iliapolo commented on src/pv.ts
> +  public reserve(namespace?: string): pvc.PersistentVolumeClaim {
We don't normally use optional positional arguments. Instead, create a `PersistentVolumeReserveOptions` interface.

Also this requires a test.

2024-04-07 09:20 UTC, iliapolo commented on src/pv.ts
> +      namespace: namespace ? namespace : this.metadata.namespace,
```suggestion
      namespace: namespace ?? this.metadata.namespace,
```

2024-04-07 09:20 UTC, iliapolo commented
Awesome, thanks for this!

2024-09-17 20:00 UTC, closed without merging