Support `restartPolicy` field in Container object
cdk8s-team/cdk8s-plus pull request #3812
Opened 2024-03-01 07:36 UTC by serhatcetinkaya

[KEP-753](https://github.com/kubernetes/enhancements/tree/e1a916745378660bafb96cb3c9f754fa793342f9/keps/sig-node/753-sidecar-containers) introduced native sidecar container support starting from kubernetes v1.28

This PR adds the field to Container object. Existing tests are working, I added one more test to make sure field is there if the property is specified

2024-04-07 08:05 UTC, iliapolo requested changes
Thanks for this! 

Can you also make sure the PR [allows changes from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)? I can't seem to update your branch from origin. Otherwise you'll have to manually update (which is also ok if you want)

2024-04-07 08:05 UTC, iliapolo commented on src/container.ts
> +   * @default - no restart policy is defined
```suggestion
   * @default - no restart policy is defined and the pod restart policy is applied
```

2024-04-07 08:05 UTC, iliapolo commented on src/container.ts
> + * This field may only be set for init containers, and the only allowed value is "Always".
How about adding a validation that normal containers don't specify this? We can do it here: 

https://github.com/cdk8s-team/cdk8s-plus/blob/0cd21c04e533e873c1698d173d395e4338e2a8ec/src/pod.ts#L192-L199

2024-04-07 08:05 UTC, iliapolo commented on test/container.test.ts
> +    expect(container).toHaveProperty('restartPolicy');
```suggestion
    expect(container.restartPolicy).toEqual('Always');
```

2024-04-15 11:50 UTC, serhatcetinkaya commented
@iliapolo thanks for the detailed check, I added all your suggestions. It should be ok now, can you give it another look please?

2024-04-18 07:14 UTC, iliapolo approved these changes

2024-04-18 07:21 UTC, merged

2024-04-18 07:21 UTC, cdk8s-automation commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|k8s-27/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/4044">](https://github.com/cdk8s-team/cdk8s-plus/pull/4044)|
|✅|k8s-28/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/4045">](https://github.com/cdk8s-team/cdk8s-plus/pull/4045)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.5.0 -->