feat(container): add capabilities to security context
cdk8s-team/cdk8s-plus pull request #3817
Opened 2024-03-01 10:53 UTC by serhatcetinkaya

adding support for capabilities in container security context. see:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#capabilities-v1-core

2024-04-07 08:13 UTC, iliapolo requested changes

2024-04-07 08:13 UTC, iliapolo commented on src/container.ts
> +        capabilities: this.capabilities,
Why not just put this in the existing return statement?

2024-04-15 12:11 UTC, serhatcetinkaya commented on src/container.ts
> +        capabilities: this.capabilities,
thanks it totally makes sense, I don't remember what I was thinking 😅 fixed

2024-04-18 07:12 UTC, iliapolo approved these changes

2024-04-18 07:31 UTC, merged

2024-04-18 07:32 UTC, cdk8s-automation commented
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|k8s-27/main|**Backport failed because of merge conflicts**<br><br>You might need to backport the following PRs to k8s-27/main:<br> - [feat(container): support `restartPolicy` field (#3812)](https://github.com/cdk8s-team/cdk8s-plus/pull/3812)|
|✅|k8s-28/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/4048">](https://github.com/cdk8s-team/cdk8s-plus/pull/4048)|

### Manual backport
To create the backport manually run:
```
backport --pr 3817
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.5.0 -->

2024-04-18 16:56 UTC, iliapolo commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|k8s-27/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/4055">](https://github.com/cdk8s-team/cdk8s-plus/pull/4055)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.5.0 -->