added revisionHistoryLimit property in DeploymentProps interface
cdk8s-team/cdk8s-plus pull request #4691
Opened 2024-09-18 19:33 UTC by parthlaw

Fixes #4254 
- This adds revisionHistoryLimit to DeploymentProps property.
- Additional change is needed to use this value instead of default value: 10.

2025-01-06 09:35 UTC, phelian commented
Hi, any indication as to when we can merge this?

2025-02-25 07:47 UTC, iliapolo requested changes

2025-02-25 07:47 UTC, iliapolo commented on src/deployment.ts
> +    this.revisionHistoryLimit = props.revisionHistoryLimit;
This is not enough though to get this included in the manifest. It also needs to added to `_toKube()`:

https://github.com/cdk8s-team/cdk8s-plus/blob/2be034ce6d68faeec22fe96cb8fda539aa020400/src/deployment.ts#L230-L242

2025-02-25 07:47 UTC, iliapolo commented on src/deployment.ts
> +    this.revisionHistoryLimit = props.revisionHistoryLimit;
We normally apply kubernetes defaults in order to surface the value in the manifest. 
 
```suggestion
    this.revisionHistoryLimit = props.revisionHistoryLimit ?? 10;
```

Also this needs a unit test which passes a custom value and asserts it indeed propagates to the manifest.

2025-02-25 07:47 UTC, iliapolo commented on src/deployment.ts
> +   * Number of desired replicasets history.
If it makes sense, we just copy the kubernetes docs. I think it makes sense here.

```suggestion
   * Specify how many old ReplicaSets for this Deployment you want to retain. The rest will be garbage-collected in the background. By default, it is 10.
```

2025-02-25 07:47 UTC, iliapolo commented on src/deployment.ts
> +  readonly revisionHistoryLimit?: number;
As a field of the deployment this shouldn't be optional, as it has a default value.

```suggestion
   */

  readonly revisionHistoryLimit: number;
```

2025-02-25 07:47 UTC, iliapolo commented
@parthlaw see comments, and apologies for the (very) late response. Hopefully you are still available to see this through.

2025-03-07 11:39 UTC, parthlaw commented
Hi, not a problem. Will address these comments.

2025-05-08 11:28 UTC, Ryu236 commented
Hi @parthlaw, thank you for creating your pull request!
Could you proceed with the modification? If you couldn't do that, I will try to handle it. 🙇

2025-05-17 06:06 UTC, Ryu236 commented
Hi @parthlaw @iliapolo,
I'd really like to use the feature in this PR, but there hasn't been any activity for about three months.
Would it be alright to address the review comments?
If so, I can push commits while keeping the original commit authorship intact.
Thanks! 🙇

2025-07-08 08:26 UTC, phelian commented
14 lines of code, and it has taken almost one year to push in. I will never create an issue in here again..

2025-08-11 17:44 UTC, Ryu236 commented
I created a new pull request #6106 
Could you check the above PR? 🙇

2025-08-18 17:11 UTC, iliapolo commented
Closed in favor of https://github.com/cdk8s-team/cdk8s-plus/pull/6106

2025-08-18 17:11 UTC, closed without merging