feat: classes for common secret types
cdk8s-team/cdk8s-plus pull request #473
Opened 2022-03-24 23:15 UTC by Chriscbr

This PR adds custom classes for the following secret types:

- service account token secrets
- basic authentication secrets
- tls secrets
- ssh authentication secrets

Closes #344

Signed-off-by: Christopher Rybicki <rybickic@amazon.com>

2022-03-27 10:51 UTC, iliapolo requested changes

2022-03-27 10:51 UTC, iliapolo commented on test/secret.test.ts
> +
Missing two tests?

- BasicAuth
- SshAuth

2022-03-27 10:51 UTC, iliapolo commented on test/secret.test.ts
> +test('Can create an ssh authentication secret', () => {
I think the name here is wrong...

```suggestion
test('Can create a service account token secret', () => {
```

2022-03-27 10:51 UTC, iliapolo commented on test/secret.test.ts
> +  const secret = new kplus.ServiceAccountTokenSecret(chart, 'BasicAuth', {
```suggestion
  const secret = new kplus.ServiceAccountTokenSecret(chart, 'ServiceAccountToken', {
```

2022-03-27 10:51 UTC, iliapolo commented on src/secret.ts
> + * @see https://docs.docker.com/engine/reference/commandline/cli/#sample-configuration-file
```suggestion
 * @see https://kubernetes.io/docs/concepts/configuration/secret/#docker-config-secrets
```

2022-03-27 10:51 UTC, iliapolo commented on src/secret.ts
> + * Create a secret for storing a certificate and its associated key.
```suggestion
 * Create a secret for storing a certificate and its associated key.
 *
 * @see https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets
```

2022-03-27 10:51 UTC, iliapolo commented on src/secret.ts
> + * Create a secret for basic authentication.
```suggestion
 * Create a secret for basic authentication.
 *
 * @see https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets
```

2022-03-27 10:51 UTC, iliapolo commented on src/secret.ts
> + * Create a secret for basic authentication.
```suggestion
 * Create a secret for basic authentication.
 *
 * @see https://kubernetes.io/docs/concepts/configuration/secret/#ssh-authentication-secrets
```

2022-03-27 10:51 UTC, iliapolo commented on src/secret.ts
> + * Create a secret for basic authentication.
```suggestion
 * Create a secret for basic authentication.
 *
 * @see https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret
```

2022-03-27 11:04 UTC, iliapolo requested changes

2022-03-27 11:04 UTC, iliapolo commented on src/secret.ts
> +      type: 'kubernetes.io/basic-auth',
```suggestion
      type: 'kubernetes.io/service-account-token',
```

2022-03-27 11:04 UTC, iliapolo commented on src/secret.ts
> +      type: 'kubernetes.io/basic-auth',
```suggestion
      type: 'kubernetes.io/ssh-auth',
```

2022-03-27 11:04 UTC, iliapolo commented on src/secret.ts
> +   * The SSH credential to use
```suggestion
   * The SSH private key to use
```

2022-03-28 21:20 UTC, Chriscbr commented
Ah I forgot committing from the GitHub UI messes up all the DCO checks -- I'm just going to squash and force push all of these commits.

2022-03-28 21:34 UTC, Chriscbr commented on test/secret.test.ts
> +
Fixed

2022-03-29 08:57 UTC, iliapolo approved these changes

2022-03-29 09:01 UTC, merged

2022-04-13 13:39 UTC, iliapolo commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|k8s-21/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/565">](https://github.com/cdk8s-team/cdk8s-plus/pull/565)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.3.1 -->

2022-04-13 14:08 UTC, iliapolo commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|k8s-20/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/568">](https://github.com/cdk8s-team/cdk8s-plus/pull/568)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.3.1 -->