feat: add support for configuring scheme in http probes
cdk8s-team/cdk8s-plus pull request #958
Opened 2022-07-19 19:08 UTC by rvshettigar

Signed-off-by: rakshith <rakshith@yahooinc.com>

Fixes #

2022-08-01 19:31 UTC, rvshettigar commented
@iliapolo Can you please take a look at this PR when you get a chance?

2022-08-30 08:47 UTC, iliapolo requested changes
@rvshettigar Thanks for this! 

Just a few minor fixups and we're good to merge

2022-08-30 08:47 UTC, iliapolo commented on src/probe.ts
> +export enum HttpGetScheme {
```suggestion
export enum ConnectionScheme {
```

2022-08-30 08:47 UTC, iliapolo commented on src/probe.ts
> +   *  @default - Defaults to HTTP.
Where possible, and if they sufficiently convey meaning, we use concrete values to describe defaults.
 
```suggestion
   *  @default HttpGetScheme.HTTP.
```

2022-08-30 08:47 UTC, iliapolo commented on src/_action.ts
> +      scheme: options.scheme,
We try surfacing k8s defaults as much as possible. It makes the manifest more clear, without having to wonder "what is the k8s default for this property". 

```suggestion
      scheme: options.scheme ?? HttpGetScheme.HTTP,
```

2022-09-01 13:02 UTC, iliapolo commented
@rvshettigar Should I give this PR another round of review?

2022-09-07 18:40 UTC, rvshettigar commented
@iliapolo  Sorry, I missed your comment. Yes please, the PR is ready for your review. Thanks.

2022-09-07 20:57 UTC, iliapolo approved these changes

2022-09-07 20:58 UTC, merged

2022-09-07 20:59 UTC, cdk8s-automation commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|k8s-22/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/1105">](https://github.com/cdk8s-team/cdk8s-plus/pull/1105)|
|✅|k8s-23/main|[<img src="https://img.shields.io/github/pulls/detail/state/cdk8s-team/cdk8s-plus/1106">](https://github.com/cdk8s-team/cdk8s-plus/pull/1106)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.3 -->